### ISSUE TITLE
What's the meaning of image pitch?

### ISSUE THREAD

**Issue by auroua** [shizenglin/Counting-with-Focus-for-Free#2]
In section 3.2, the equation `4` contains a  `|Pj,i|` which denotes the number of point annotations in patch j. What's the image pitch in this place and how to get the image pitch.

**Comment by shizenglin** [comment]
Hi, image patch is randomly extracted from training image, the size of patch is 128x128 in our paper.

**Comment by auroua** [comment]
Thanks!
