### ISSUE TITLE
How to generate the goundtruth density map for ShanghaiTech_partB?

### ISSUE THREAD

**Issue by huangxGo** [shizenglin/Counting-with-Focus-for-Free#4]
Thanks for the nice work!
But I'm confused with the kernel computation for ShanghaiTech_partB, when you said you set the Gaussian kernel variance sigma=5 (a fixed sigma, I think?), following CSRNet.However, I found that   CSRNet use the geometry-adaptive kernels, whose sigma is corresponding to the average distance of k nearest neighbors.
So which is the way to compute the kernel variance in your work?Thanks for your patience!

**Comment by shizenglin** [comment]
Hi,

See the Table 2 in CSRNet. They indeed use a fixed sigma for shanghaiTech partB. I set the Gaussian kernel variance sigma=5.

**Comment by huangxGo** [comment]
> Hi,
> 
> See the Table 2 in CSRNet. They indeed use a fixed sigma for shanghaiTech partB. I set the Gaussian kernel variance sigma=5.

Oh you're right! Thanks for reply!
