### ISSUE TITLE
How to compute the global density step size L?

### ISSUE THREAD

**Issue by huangxGo** [shizenglin/Counting-with-Focus-for-Free#5]
https://github.com/shizenglin/Counting-with-Focus-for-Free/blob/8081d0f6c533f03010e013c2205dc1821cc8fa7a/code/utils.py#L117
In this line, I found that there is no code for computing the global density step size L.
Could you please share the code or just share the global density step size L for datasets, SHHA etc?
THANKS!

**Comment by shizenglin** [comment]
Hi, 

L can be easily estimated by equation 5 in the paper. For SHanghai PartA, L= 20, partB, L= 8, Trancos, L=11, DCC, L=3.

**Comment by huangxGo** [comment]
> Hi,
> 
> L can be easily estimated by equation 5 in the paper. For SHanghai PartA, L= 20, partB, L= 8, Trancos, L=11, DCC, L=3.

Thank you so much!
