### ISSUE TITLE
Question about Segmentation Map Generation.

### ISSUE THREAD

**Issue by YujunXie** [shizenglin/Counting-with-Focus-for-Free#6]
https://github.com/shizenglin/Counting-with-Focus-for-Free/blob/8081d0f6c533f03010e013c2205dc1821cc8fa7a/data/segmentation.m#L12

Thanks for your code!  Have some question about the generation of segmentation map.
Where is variable `image_info` defined?  Is the ground_truth density map regenerated with `location` variable?

**Comment by shizenglin** [comment]
Hi,

image_info from load(position_head_path);  
load(position_head_path); This would create some variables, which varies from different dataset.

**Comment by YujunXie** [comment]
Thanks a lot!
